import Head from "next/head";
import { DataContext } from "../store/GlobalState";
import { useState, useContext, useEffect } from "react";

export default function Helper() {
	const { state, dispatch } = useContext(DataContext);

	return (
		<div>
			<Head>
				<title>Frequency Sorting</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div class="container p-5">
				<div class="flex text-xl border-b-2 border-black pb-1 ">
					<span class="bg-gray-700 px-2   text-xl rounded-full text-red-200">1</span>
					<p className="ml-2"> Set Frequency list</p>
				</div>
				<div className="ml-2 text-md text-gray-900 mt-1">
					<p>
						{" "}
						<span className="text-xl font-bold text-red-700">&#x2022;</span> Here are 2 ways to set
						the frequency list .
					</p>
					<p className="ml-4">
						<span className="font-bold"> I</span> : It can be added manually with a variable
						frequency and band by pressing:{" "}
						<button className="bg-gray-800  px-1.5 rounded-xl mb-1 text-gray-200">
							Add Frequency
						</button>
					</p>
					<p className="ml-4">
						<span className="font-bold"> II</span> : It can be imported from excell, with a standard
						format that can be downloaded by pressing:{" "}
						<button className="bg-gray-800  px-1 rounded-xl text-gray-200">Excell Template </button>
					</p>
					<p>
						{" "}
						<span className="text-xl font-bold text-red-700">&#x2022; </span>
						After the list of frequencies has been set, they are filtered automatically and changes
						can be made from the interface. To erase all data, have to press{" "}
						<button className="bg-red-700  px-1.5 rounded-xl mb-1 text-gray-200">
							Erase all data
						</button>
					</p>
				</div>

				{/*Sectiune 1 Final ============================================================================== */}

				<div class="flex text-xl my-2 border-b-2 border-black pb-1 ">
					<span class="bg-gray-700 px-2   text-xl rounded-full text-red-200">2</span>
					<p className="ml-2"> Frequency Processing</p>
				</div>
				<div className="ml-2 text-md text-gray-900 mt-1">
					<p>
						{" "}
						<span className="text-xl font-bold text-red-700">&#x2022;</span> Here are 2 sections,
						the first one with the previously frequencies list, and the second with processing
						parameters
					</p>
					<p>
						{" "}
						<span className="text-xl font-bold text-red-700">&#x2022;</span> To sort the
						frequencies, it is necessary to set a set of parameters according to the necessity.
					</p>
					<p>
						{" "}
						<span className="text-xl ml-4 font-bold text-green-700">&#x2022; </span>
						The number of harmonics that have to be between 1 and 7.
					</p>{" "}
					<p>
						{" "}
						<span className="text-xl ml-4 font-bold text-green-700">&#x2022; </span>
						The number of frequencies in the generated set.
					</p>
					<p>
						{" "}
						<span className="text-xl ml-4 font-bold text-green-700">&#x2022; </span>
						The number of frequencies taken into account in intermodulation generation.
					</p>
					<p>
						{" "}
						<span className="text-xl ml-4 font-bold text-green-700">&#x2022; </span>
						The number of adjacent channels for base chanel that can be 1, 2, 3, 4, 5, 10.
					</p>
					<p>
						{" "}
						<span className="text-xl ml-4 font-bold text-green-700">&#x2022; </span>
						The number of adjacent channels for intermodulation chanel.
					</p>
					<p>
						{" "}
						<span className="text-xl font-bold text-red-700">&#x2022; </span>
						After setting the parameters, press{" "}
						<button className="bg-gray-800  px-1.5 rounded-xl mb-1 text-gray-200">
							Generate set
						</button>{" "}
						and if it corresponds to the need press{" "}
						<button className="bg-gray-800  px-1.5 rounded-xl mb-1 text-gray-200">Save set</button>
					</p>
				</div>

				{/*Sectiune 2 Final ============================================================================== */}

				<div class="flex text-xl my-2 border-b-2 border-black pb-1 ">
					<span class="bg-gray-700 px-2   text-xl rounded-full text-red-200">3</span>
					<p className="ml-2"> Output Lists Saving</p>
				</div>
				<div className="ml-2 text-md text-gray-900 mt-1">
					<p>
						{" "}
						<span className="text-xl font-bold text-red-700">&#x2022;</span> After press{" "}
						<button className="bg-gray-800  px-1 rounded-xl text-gray-200">Output list {" "}</button>
						{" "}the processed frequency sets will appear on the display, at this moment we have 2
						options
					</p>

					<p>
						{" "}
						<span className=" font-bold ml-4 text-black-700">I : </span>
						Export sets as Excell table.
					</p>
					<p>
						{" "}
						<span className=" font-bold ml-4 text-black-700">II : </span>
						Delete Sets and generate new ones.
					</p>
				</div>

				{/*Sectiune 3 Final ============================================================================== */}
				<div class="flex text-xl my-2 border-b-2 border-black pb-1 ">
					<span class="bg-gray-700 px-2   text-xl rounded-full text-red-200">*</span>
					<p className="ml-2">Harmonics</p>
				</div>
				<div className="ml-2 text-md text-gray-900 mt-1">
					<p>
						{" "}
						<span className="text-xl font-bold text-black-700">&#x2022; </span>A maximum of 1000
						harmonics are displayed in this menu, the number is limited by the rendering capacity of
						the Browser.
					</p>
					<span className="text-xl font-bold text-black-700">&#x2022; </span> This menu helps to
					visualize the generation mode of the interference channels
				</div>
				{/*Sectiune 4 Final ============================================================================== */}
			</div>
		</div>
	);
}
